// AUTO-GENERATED by scripts/generate-system-provider-ids.ts — DO NOT EDIT.
// Regenerate with `pnpm gen:system-provider-ids`. Source of truth:
// packages/provider-registry/data/providers.json (every provider id except the
// agent/CLI-only backends in CLI_ONLY_PROVIDER_IDS in that script).

import * as z from 'zod'

export const SystemProviderIdSchema = z.enum([
  'bimhu'
])

export type SystemProviderId = z.infer<typeof SystemProviderIdSchema>

export const isSystemProviderId = (id: string): id is SystemProviderId => {
  return SystemProviderIdSchema.safeParse(id).success
}

export const SystemProviderIds = {
  bimhu: 'bimhu'
} as const satisfies Record<SystemProviderId, SystemProviderId>
